% Create options structure for this project
%

opts = {};

opts.basepath = {'PNASData/pMFG_bilat_4.14/',...
                          'PNASData/pMFG_left_5.11/',...
                          'PNASData/aMFG_bilat_4.14/', ...
                          'PNASData/aMFG_left_5.11/', ...
                          'PNASResting/'};
opts.inputFiles = {'PNASData/pMFG_bilat_4.14/*pMFG*',...
                          'PNASData/pMFG_left_5.11/*pMFG*',...
                          'PNASData/aMFG_bilat_4.14/*aMFG*', ...
                          'PNASData/aMFG_left_5.11/*aMFG*', ...
                          'PNASResting/*RESTING*'};
opts.conditions = {'R_pMFG','L_pMFG','R_aMFG','L_aMFG','Resting'};
opts.outputFiles = strcat('Data/',opts.conditions, '_', datestr(now,'mmm-dd-yyyy'))
save('pcnets_options','opts')
